### ISSUE TITLE
Error: "No targets specified and no makefile found.  Stop."

### ISSUE THREAD

**Issue by trevordmiller** [dgraham/vim-eslint#1]
I like the idea of this plugin, but am struggling to get it to work. I have installed the plugin, and have added the following leader command:

```
nnoremap <leader>l :make<cr>:cwindow<cr>:redraw!<cr>
```

But when I run it and open the quickfix list, I only see:

![image](https://user-images.githubusercontent.com/5497885/44555697-b2b0e000-a6f3-11e8-8d6c-a308ec789a17.png)

I have eslint installed in my project's (vim current directory's) `node_modules` (but not globally).

**Comment by dgraham** [comment]
This is the output from `make`, which means `makeprg` isn't [being set](https://github.com/dgraham/vim-eslint/blob/master/compiler/eslint.vim#L6) by the plugin. This could be caused by using an older version of Vim that doesn't support packages under `~/.vim/pack`. 

Another possible cause is that file type detection isn't running for `.js` files so the [compiler settings](https://github.com/dgraham/vim-eslint/blob/ef7d648235d372c724c0b140016399a43d6b6976/ftdetect/javascript.vim#L1) aren't applied to the buffer. Make sure this is enabled in your `~/.vimrc` file.

```vim
set nocompatible
filetype plugin on
```

**Comment by trevordmiller** [comment]
I'm on latest Vim and had the required settings. I realized that the problem is that I can't call `:make` unless I have a `.js` buffer open. I was calling it with netrw open to the root of my project. It makes sense now that `filetype` will not be set to `.js` which this plugin requires to set `:make` to eslint. Thanks for your time.

**Comment by trevordmiller** [comment]
However, when I remove eslint globally (I'm trying to move to only using project specific `node_modules`), now when I run `:make` I get: `/bin/bash: eslint: command not found`

![image](https://user-images.githubusercontent.com/5497885/44562970-4d6fe580-a719-11e8-961f-cad3ffdc9c2b.png)

I've double checked the `eslint` binary does not exist globally, but it does exist in `node_modules` at the path used by [the plugin](https://github.com/dgraham/vim-eslint/blob/master/compiler/eslint.vim#L6) and is working inside of npm scripts:

![image](https://user-images.githubusercontent.com/5497885/44563129-ff0f1680-a719-11e8-998e-e40a25bcce12.png)

![image](https://user-images.githubusercontent.com/5497885/44562897-ef430280-a718-11e8-92ca-47e87ea5fae2.png)

![image](https://user-images.githubusercontent.com/5497885/44562816-8fe4f280-a718-11e8-9376-7cbb2bdd61fd.png)

Do you know of a reason why the plugin would no longer work when `eslint` is removed from a global install but is still in the project's `node_modules`? Perhaps [this line](https://github.com/dgraham/vim-eslint/blob/master/compiler/eslint.vim#L4)?

**Comment by dgraham** [comment]
It looks like `makeprg` isn't set by the plugin or is overridden somewhere. The clue is the bare eslint reference and the incorrect format option in `:eslint -f compact …`. This is being set outside of the plugin.

Open a `.js` file buffer and run `:set makeprg` to display the value. It should look like this.

`makeprg=./node_modules/.bin/eslint --no-color -f unix $*`

**Comment by trevordmiller** [comment]
@dgraham Yep that looks to be the problem - my `:set makeprg` output is `makeprg=eslint -f compact %`, so it isn't pointing to the local `./node_modules` version. I realize this isn't related to your plugin but do you have any idea how I might debug where this is being set and/or fix it? I have a fairly minimal .vimrc:
https://github.com/trevordmiller/dotfiles/blob/master/files/.vimrc

**Comment by trevordmiller** [comment]
Also, not sure if it helps but I'm using vim-plug instead of `.vim/pack`. I've tested both with this plugin and it doesn't seem to make a difference.

**Comment by dgraham** [comment]
You might try a manual binary search through the [list of plugins](https://github.com/trevordmiller/dotfiles/blob/b91b2e80118cc53c36b3cb6c7e3d060ed63c9a7e/files/.vimrc#L6-L20) by commenting out half of them, restarting vim, and trying `:set makeprg`. If it works, you know one of the plugins in the first half is the culprit and uncomment half of those before trying again.

Running `vim -u NONE` will launch it without running any `.vimrc` customizations, which can be helpful just to verify the default state isn't configuring something unexpected.

Another idea to try is copying what the plugin does directly into the bottom of your `.vimrc` file. That would eliminate plugin managers and load path issues as variables. The plugin is really just two config files that could easily be tested inside a `.vimrc`. That's how I first ran them before creating the plugin.

**Comment by trevordmiller** [comment]
Thank you for the tips! I'll give them a try :) I appreciate your time.

**Comment by trevordmiller** [comment]
It was ALE, which I need. So I uninstalled `vim-eslint` and added these to my vimrc:

```
set makeprg=./node_modules/.bin/eslint\ --no-color\ -f\ unix\ $*
set errorformat=%A%f:%l:%c:%m,%-G%.%#
```

```
nnoremap <leader>l :make .<cr>:copen<cr>:redraw!<cr>
```
